# 使用当前 IDEA 的配置目录
idea.config.path=${user.home}/Library/Application Support/JetBrains/IntelliJIdea2023.2
idea.system.path=${user.home}/Library/Caches/JetBrains/IntelliJIdea2023.2
idea.plugins.path=${idea.config.path}/plugins
idea.log.path=${idea.system.path}/log 